from inputs_v2.application.design_brain_families import DesignFamily, V1_FAMILY_PRIORITY


V1_CONTRACT_FAMILIES = {
    "EXACT_STOP_PROVEN",
    "LOCKED_NO_REPAIR",
    "GEOMETRY_DETAILING_GOVERNS",
    "BENDING_AND_SHEAR_FAIL_GOVERN",
    "BENDING_FAIL_SHEAR_OVERDESIGN_GOVERNS",
    "SHEAR_FAIL_BENDING_OPTIMISE_GOVERNS",
    "BENDING_FAIL_GOVERNS",
    "SHEAR_FAIL_GOVERNS",
    "SERVICEABILITY_GOVERNS",
    "COMBINED_OVERDESIGN",
    "BENDING_OVERDESIGN_GOVERNS",
    "SHEAR_OVERDESIGN_GOVERNS",
    "TARGET_BAND_REACHED",
}


def test_v2_registry_preserves_v1_contract_families_and_adds_typed_no_load_state() -> None:
    assert {family.value for family in DesignFamily} == V1_CONTRACT_FAMILIES | {"INPUT_REQUIRED"}
    assert tuple(family.value for family in V1_FAMILY_PRIORITY) == (
        "INPUT_REQUIRED", "EXACT_STOP_PROVEN", "LOCKED_NO_REPAIR", "GEOMETRY_DETAILING_GOVERNS",
        "BENDING_AND_SHEAR_FAIL_GOVERN", "BENDING_FAIL_SHEAR_OVERDESIGN_GOVERNS",
        "SHEAR_FAIL_BENDING_OPTIMISE_GOVERNS", "BENDING_FAIL_GOVERNS", "SHEAR_FAIL_GOVERNS",
        "SERVICEABILITY_GOVERNS", "COMBINED_OVERDESIGN", "BENDING_OVERDESIGN_GOVERNS",
        "SHEAR_OVERDESIGN_GOVERNS", "TARGET_BAND_REACHED",
    )
