from pathlib import Path

path = Path('widgets_helpers.py')
source = path.read_text(encoding='utf-8-sig')
anchor = '''div[data-testid="stVerticalBlock"]:has(\n  > div[data-testid="stElementContainer"] [data-calc-uid]\n) div[data-testid="stExpander"] details[open]:has(span.step-fail) > div {\n  box-shadow: inset 4px 0 0 #dc3545 !important;\n  background: rgba(220,53,69,0.018) !important;\n}\n</style>\n'''
replacement = '''div[data-testid="stVerticalBlock"]:has(\n  > div[data-testid="stElementContainer"] [data-calc-uid]\n) div[data-testid="stExpander"] details[open]:has(span.step-fail) > div {\n  box-shadow: inset 4px 0 0 #dc3545 !important;\n  background: rgba(220,53,69,0.018) !important;\n}\n\n/* Technical-basis trigger: calculation cards use one clear teaching CTA.\n   Keep ordinary app popovers unchanged by scoping this to calc-card stacks. */\ndiv[data-testid="stVerticalBlock"]:has(\n  > div[data-testid="stElementContainer"] [data-calc-uid]\n) div[data-testid="stExpander"] div[data-testid="stPopover"] button[kind="secondary"],\ndiv[data-testid="stVerticalBlock"]:has(\n  > div[data-testid="stElementContainer"] [data-calc-uid]\n) div[data-testid="stExpander"] div[data-testid="stPopover"] button[data-testid="baseButton-secondary"] {\n  border: 1px solid rgba(31,119,180,0.32) !important;\n  border-radius: 999px !important;\n  background: rgba(31,119,180,0.055) !important;\n  color: #1f5f8f !important;\n  padding: 0.28rem 0.62rem !important;\n  min-height: 1.85rem !important;\n  font-size: 0 !important;\n  line-height: 1 !important;\n  font-weight: 600 !important;\n}\ndiv[data-testid="stVerticalBlock"]:has(\n  > div[data-testid="stElementContainer"] [data-calc-uid]\n) div[data-testid="stExpander"] div[data-testid="stPopover"] button[kind="secondary"]::before,\ndiv[data-testid="stVerticalBlock"]:has(\n  > div[data-testid="stElementContainer"] [data-calc-uid]\n) div[data-testid="stExpander"] div[data-testid="stPopover"] button[data-testid="baseButton-secondary"]::before {\n  content: "ⓘ Understand the technical basis";\n  display: inline !important;\n  font-size: 0.78rem !important;\n  line-height: 1.1 !important;\n  white-space: nowrap !important;\n}\ndiv[data-testid="stVerticalBlock"]:has(\n  > div[data-testid="stElementContainer"] [data-calc-uid]\n) div[data-testid="stExpander"] div[data-testid="stPopover"] button[kind="secondary"]:hover,\ndiv[data-testid="stVerticalBlock"]:has(\n  > div[data-testid="stElementContainer"] [data-calc-uid]\n) div[data-testid="stExpander"] div[data-testid="stPopover"] button[data-testid="baseButton-secondary"]:hover {\n  border-color: rgba(31,119,180,0.55) !important;\n  background: rgba(31,119,180,0.10) !important;\n  color: #155a8a !important;\n}\n</style>\n'''
if source.count(anchor) != 1:
    raise SystemExit('calc-card CSS anchor changed unexpectedly')
source = source.replace(anchor, replacement, 1)
path.write_text(source, encoding='utf-8')
